# Generated by Django 5.0.1 on 2026-01-25 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rate_to_km', models.DecimalField(decimal_places=4, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FailedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('error', models.TextField()),
                ('retryable', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Failed Requests',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('plan', models.CharField(choices=[('Starter', 'Starter'), ('Professional', 'Professional'), ('Business', 'Business'), ('Enterprise', 'Enterprise')], default='Starter', max_length=20)),
                ('jib', models.CharField(max_length=13)),
                ('racun', models.CharField(max_length=20)),
                ('registrovan', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Korisnici',
            },
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.CharField(max_length=20)),
                ('datum', models.DateField()),
                ('klijent', models.CharField(max_length=200)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Na čekanju', 'Na čekanju'), ('Plaćena', 'Plaćena')], default='Na čekanju', max_length=20)),
                ('opis', models.TextField(blank=True)),
                ('fajl', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakture', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Fakture',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_reminder', 'Podsjetnik za plaćanje'), ('invoice_due', 'Faktura dospjeva'), ('monthly_summary', 'Mjesečni izvještaj'), ('annual_report', 'Godišnji izvještaj')], max_length=30)),
                ('scheduled_date', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_body', models.TextField()),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Email Notifications',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('klijent', models.CharField(max_length=200)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('svrha', models.CharField(max_length=200)),
                ('datum_transakcije', models.DateField()),
                ('confidence', models.IntegerField(default=95)),
                ('potvrdjeno', models.BooleanField(default=False)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Email Inbox',
                'ordering': ['-datum_transakcije'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_deadline', 'Rok plaćanja'), ('invoice_due', 'Faktura dospjeva'), ('meeting', 'Sastanak'), ('reminder', 'Podsjetnik')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Bilans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_mjesec', models.CharField(max_length=7)),
                ('do_mjesec', models.CharField(max_length=7)),
                ('ukupan_prihod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porez', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doprinosi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fajl', models.FileField(upload_to='bilans/')),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('datum_isteka', models.DateTimeField()),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilansi', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Bilansi',
                'ordering': ['-datum_kreiranja'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjesec', models.CharField(max_length=7)),
                ('predicted_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Predictive Analytics',
                'ordering': ['mjesec'],
            },
        ),
        migrations.CreateModel(
            name='Prihod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjesec', models.CharField(max_length=7)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prihodi', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Prihodi',
                'ordering': ['mjesec'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Uplatnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('primalac', models.CharField(choices=[('PURS', 'Poreska uprava RS'), ('FZO RS', 'Fond zdravstva RS')], max_length=20)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('svrha', models.CharField(max_length=200)),
                ('poziv_na_broj', models.CharField(blank=True, max_length=50)),
                ('fajl', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uplatnice', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Uplatnice',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Faktura'), ('receipt', 'Račun'), ('contract', 'Ugovor'), ('other', 'Ostalo')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_docs', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Uploaded Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('sr', 'Srpski'), ('en', 'English')], default='sr', max_length=2)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('payment_reminders', models.BooleanField(default=True)),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='GodisnjiIzvjestaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.IntegerField()),
                ('ukupan_prihod', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ukupan_porez', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ukupni_doprinosi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('neto_dohodak', models.DecimalField(decimal_places=2, max_digits=12)),
                ('broj_faktura', models.IntegerField()),
                ('broj_klijenata', models.IntegerField()),
                ('fajl_pdf', models.FileField(upload_to='godisnji_izvjestaji/')),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godisnji_izvjestaji', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Godišnji izvještaji',
                'ordering': ['-godina'],
                'unique_together': {('korisnik', 'godina')},
            },
        ),
    ]
