# Generated by Django 5.0.1 on 2026-01-26 20:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rate_to_km', models.DecimalField(decimal_places=4, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FailedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('error', models.TextField()),
                ('retryable', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Failed Requests',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_fakture', models.CharField(max_length=50, verbose_name='Broj fakture')),
                ('datum_izdavanja', models.DateField(verbose_name='Datum izdavanja')),
                ('mjesto_izdavanja', models.CharField(blank=True, max_length=200, verbose_name='Mjesto izdavanja')),
                ('izdavalac_naziv', models.CharField(max_length=300, verbose_name='Naziv izdavaoca')),
                ('izdavalac_adresa', models.CharField(max_length=300, verbose_name='Adresa izdavaoca')),
                ('izdavalac_mjesto', models.CharField(max_length=200, verbose_name='Mjesto izdavaoca')),
                ('izdavalac_jib', models.CharField(blank=True, max_length=20, verbose_name='JIB izdavaoca')),
                ('izdavalac_iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN izdavaoca')),
                ('izdavalac_racun', models.CharField(blank=True, max_length=50, verbose_name='Račun izdavaoca')),
                ('primalac_naziv', models.CharField(max_length=300, verbose_name='Naziv primaoca')),
                ('primalac_adresa', models.CharField(max_length=300, verbose_name='Adresa primaoca')),
                ('primalac_mjesto', models.CharField(max_length=200, verbose_name='Mjesto primaoca')),
                ('napomena', models.TextField(blank=True, verbose_name='Napomena')),
                ('valuta', models.CharField(choices=[('BAM', 'KM'), ('EUR', 'EUR'), ('USD', 'USD')], default='USD', max_length=3, verbose_name='Valuta')),
                ('ukupno_bez_pdv', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ukupno bez PDV')),
                ('pdv_iznos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Iznos PDV')),
                ('ukupno_sa_pdv', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ukupno sa PDV')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('issued', 'Izdato'), ('paid', 'Plaćeno'), ('cancelled', 'Stornirano')], default='draft', max_length=20, verbose_name='Status')),
                ('datum_placanja', models.DateField(blank=True, null=True, verbose_name='Datum plaćanja')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Fakture',
                'db_table': 'faktura',
                'ordering': ['-datum_izdavanja', '-broj_fakture'],
                'unique_together': {('user', 'broj_fakture')},
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=200)),
                ('plan', models.CharField(choices=[('Starter', 'Starter'), ('Professional', 'Professional'), ('Business', 'Business'), ('Enterprise', 'Enterprise')], default='Starter', max_length=20)),
                ('jib', models.CharField(max_length=13)),
                ('racun', models.CharField(max_length=20)),
                ('registrovan', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Korisnici',
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_reminder', 'Podsjetnik za plaćanje'), ('invoice_due', 'Faktura dospjeva'), ('monthly_summary', 'Mjesečni izvještaj'), ('annual_report', 'Godišnji izvještaj')], max_length=30)),
                ('scheduled_date', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_body', models.TextField()),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Email Notifications',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('klijent', models.CharField(max_length=200)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('svrha', models.CharField(max_length=200)),
                ('datum_transakcije', models.DateField()),
                ('confidence', models.IntegerField(default=95)),
                ('potvrdjeno', models.BooleanField(default=False)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Email Inbox',
                'ordering': ['-datum_transakcije'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment_deadline', 'Rok plaćanja'), ('invoice_due', 'Faktura dospjeva'), ('meeting', 'Sastanak'), ('reminder', 'Podsjetnik')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Bilans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_mjesec', models.CharField(max_length=7)),
                ('do_mjesec', models.CharField(max_length=7)),
                ('ukupan_prihod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porez', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doprinosi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fajl', models.FileField(upload_to='bilans/')),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('datum_isteka', models.DateTimeField()),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilansi', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Bilansi',
                'ordering': ['-datum_kreiranja'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjesec', models.CharField(max_length=7)),
                ('predicted_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Predictive Analytics',
                'ordering': ['mjesec'],
            },
        ),
        migrations.CreateModel(
            name='Prihod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjesec', models.CharField(max_length=7)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prihodi', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Prihodi',
                'ordering': ['mjesec'],
            },
        ),
        migrations.CreateModel(
            name='StavkaFakture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveIntegerField(verbose_name='Redni broj')),
                ('opis', models.CharField(max_length=500, verbose_name='Opis')),
                ('jedinica_mjere', models.CharField(default='unit', max_length=50, verbose_name='Jedinica mjere')),
                ('kolicina', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Količina')),
                ('cijena_po_jedinici', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cijena po jedinici')),
                ('pdv_stopa', models.IntegerField(default=0, verbose_name='PDV stopa')),
                ('ukupna_cijena', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ukupna cijena bez PDV')),
                ('pdv_iznos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PDV iznos')),
                ('ukupna_cijena_sa_pdv', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ukupna cijena sa PDV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faktura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stavke', to='core.faktura', verbose_name='Faktura')),
            ],
            options={
                'verbose_name': 'Stavka fakture',
                'verbose_name_plural': 'Stavke fakture',
                'db_table': 'stavka_fakture',
                'ordering': ['redni_broj'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Uplatnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('primalac', models.CharField(choices=[('PURS', 'Poreska uprava RS'), ('FZO RS', 'Fond zdravstva RS')], max_length=20)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('svrha', models.CharField(max_length=200)),
                ('poziv_na_broj', models.CharField(blank=True, max_length=50)),
                ('fajl', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uplatnice', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Uplatnice',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Faktura'), ('receipt', 'Račun'), ('contract', 'Ugovor'), ('other', 'Ostalo')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_docs', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Uploaded Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('sr', 'Srpski'), ('en', 'English')], default='sr', max_length=2)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('payment_reminders', models.BooleanField(default=True)),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency')),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='GodisnjiIzvjestaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godina', models.IntegerField()),
                ('ukupan_prihod', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ukupan_porez', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ukupni_doprinosi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('neto_dohodak', models.DecimalField(decimal_places=2, max_digits=12)),
                ('broj_faktura', models.IntegerField()),
                ('broj_klijenata', models.IntegerField()),
                ('fajl_pdf', models.FileField(upload_to='godisnji_izvjestaji/')),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godisnji_izvjestaji', to='core.korisnik')),
            ],
            options={
                'verbose_name_plural': 'Godišnji izvještaji',
                'ordering': ['-godina'],
                'unique_together': {('korisnik', 'godina')},
            },
        ),
    ]
