# Generated by Django 5.0.1 on 2026-01-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prihod',
            options={'ordering': ['-datum', '-mjesec'], 'verbose_name_plural': 'Prihodi i Rashodi'},
        ),
        migrations.AddField(
            model_name='prihod',
            name='datum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prihod',
            name='izvod_fajl',
            field=models.FileField(blank=True, null=True, upload_to='izvodi/'),
        ),
        migrations.AddField(
            model_name='prihod',
            name='opis',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='prihod',
            name='vrsta',
            field=models.CharField(choices=[('prihod', 'Prihod'), ('rashod', 'Rashod')], default='prihod', max_length=10),
        ),
    ]
