# Generated by Django 5.0.1 on 2026-01-30 12:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_prihod_options_prihod_datum_prihod_izvod_fajl_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='tip_preduzetnika',
            field=models.CharField(choices=[('mali', 'Mali preduzetnik (2% mjesečno)'), ('veliki', 'Veliki preduzetnik (10% godišnje u martu)')], default='mali', help_text='Odaberite tip preduzetnika za izračunavanje poreza', max_length=10, verbose_name='Tip preduzetnika'),
        ),
        migrations.CreateModel(
            name='SistemskiParametri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjesecni_doprinosi', models.DecimalField(decimal_places=2, default=Decimal('466.00'), help_text='Lični doprinosi koji se koriste pri kreiranju uplatnice', max_digits=10, verbose_name='Mjesečni doprinosi (KM)')),
                ('porez_mali_preduzetnik', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Plaća se mjesečno', max_digits=5, verbose_name='Porez za malog preduzetnika (%)')),
                ('porez_veliki_preduzetnik', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Plaća se godišnje', max_digits=5, verbose_name='Porez za velikog preduzetnika (%)')),
                ('mjesec_placanja_poreza', models.IntegerField(default=3, help_text='Broj mjeseca (1-12), default: 3 = Mart', verbose_name='Mjesec plaćanja poreza za velike preduzetnike')),
                ('zadnje_azurirano', models.DateTimeField(auto_now=True)),
                ('azurirao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sistemski parametri',
                'verbose_name_plural': 'Sistemski parametri',
            },
        ),
    ]
