# Generated by Django 5.0.1 on 2026-01-30 12:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_korisnik_tip_preduzetnika_sistemskiparametri'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemskiparametri',
            name='prag_mali_preduzetnik',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Do ovog iznosa korisnik je mali preduzetnik (2%), preko je veliki (10%)', max_digits=12, verbose_name='Prag za malog preduzetnika (KM godišnje)'),
        ),
    ]
