# Generated by Django 5.0.1 on 2026-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sistemskiparametri_prag_mali_preduzetnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='faktura',
            name='primalac_jib',
            field=models.CharField(blank=True, help_text='JIB broj firme za koju se izdaje faktura (opcionalno)', max_length=13, null=True, verbose_name='JIB primaoca (firme)'),
        ),
    ]
