# Generated by Django 5.0.1 on 2026-01-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_faktura_primalac_jib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='valuta',
            field=models.CharField(choices=[('BAM', 'KM'), ('EUR', 'EUR'), ('USD', 'USD')], default='BAM', max_length=3, verbose_name='Valuta'),
        ),
    ]
