# Generated by Django 5.0.1 on 2026-02-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_faktura_valuta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200, verbose_name='Naziv banke')),
                ('skraceni_naziv', models.CharField(max_length=50, verbose_name='Skraćeni naziv')),
                ('racun_doprinosi', models.CharField(help_text='Račun Poreske uprave za uplate doprinosa', max_length=30, verbose_name='Račun za doprinose')),
                ('racun_porez', models.CharField(help_text='Račun Poreske uprave za uplate poreza', max_length=30, verbose_name='Račun za porez')),
                ('primalac_doprinosi', models.CharField(default='PORESKA UPRAVA REPUBLIKE SRPSKE', max_length=300, verbose_name='Primalac - Doprinosi')),
                ('primalac_porez', models.CharField(default='PORESKA UPRAVA REPUBLIKE SRPSKE', max_length=300, verbose_name='Primalac - Porez')),
                ('poziv_doprinosi', models.CharField(blank=True, help_text='Ako je različit od JIB-a', max_length=50, verbose_name='Poziv na broj (doprinosi)')),
                ('poziv_porez', models.CharField(blank=True, help_text='Ako je različit od JIB-a', max_length=50, verbose_name='Poziv na broj (porez)')),
                ('model_doprinosi', models.CharField(default='97', max_length=2, verbose_name='Model (doprinosi)')),
                ('model_porez', models.CharField(default='97', max_length=2, verbose_name='Model (porez)')),
                ('svrha_doprinosi_template', models.CharField(default='Lični doprinosi za {mjesec}/{godina}', help_text='Koristi {mjesec} i {godina} za dinamički tekst', max_length=200, verbose_name='Template svrhe - Doprinosi')),
                ('svrha_porez_template', models.CharField(default='Porez na prihod za {godina}', max_length=200, verbose_name='Template svrhe - Porez')),
                ('aktivna', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('zadnje_azurirano', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banka',
                'verbose_name_plural': 'Banke',
                'ordering': ['naziv'],
            },
        ),
    ]
