# Generated by Django 5.0.1 on 2026-02-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_banka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banka',
            name='model_doprinosi',
        ),
        migrations.RemoveField(
            model_name='banka',
            name='model_porez',
        ),
    ]
