# Generated by Django 5.0.1 on 2026-02-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_banka_model_doprinosi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='is_trial_extended',
            field=models.BooleanField(default=False, help_text='Da li je admin ručno produžio trial period', verbose_name='Trial produžen'),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='trial_end_date',
            field=models.DateField(blank=True, help_text='Automatski se postavlja 30 dana od registracije', null=True, verbose_name='Datum isteka trial perioda'),
        ),
    ]
