# Generated by Django 5.0.1 on 2026-02-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_korisnik_is_trial_extended_korisnik_trial_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailinbox',
            options={'ordering': ['-datum_prijema'], 'verbose_name_plural': 'Email Inbox'},
        ),
        migrations.RenameField(
            model_name='emailinbox',
            old_name='datum_kreiranja',
            new_name='datum_prijema',
        ),
        migrations.RenameField(
            model_name='emailinbox',
            old_name='potvrdjeno',
            new_name='procesuirano',
        ),
        migrations.RemoveField(
            model_name='emailinbox',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='emailinbox',
            name='datum_transakcije',
        ),
        migrations.RemoveField(
            model_name='emailinbox',
            name='iznos',
        ),
        migrations.RemoveField(
            model_name='emailinbox',
            name='klijent',
        ),
        migrations.RemoveField(
            model_name='emailinbox',
            name='svrha',
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='pdf_fajl',
            field=models.FileField(blank=True, null=True, upload_to='inbox_pdf/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_poruke', to='core.korisnik'),
        ),
    ]
