# Generated by Django 5.0.1 on 2026-02-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_emailinbox_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='korisnik',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='default_currency',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='korisnik',
        ),
        migrations.AlterModelOptions(
            name='emailinbox',
            options={'ordering': ['-datum_prijema'], 'verbose_name': 'Email Inbox', 'verbose_name_plural': 'Email Inbox'},
        ),
        migrations.RemoveField(
            model_name='emailinbox',
            name='body_text',
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='banka_naziv',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banka'),
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='confidence',
            field=models.IntegerField(default=0, verbose_name='AI Pouzdanost (%)'),
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='datum_odobravanja',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Odobreno'),
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='pdf_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='PDF Hash (za duplikat detekciju)'),
        ),
        migrations.AddField(
            model_name='emailinbox',
            name='transakcije_json',
            field=models.JSONField(blank=True, help_text='Lista transakcija: [{datum, opis, iznos, tip}, ...]', null=True, verbose_name='Parsovane transakcije'),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='datum_prijema',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Primljeno'),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='from_email',
            field=models.EmailField(max_length=254, verbose_name='Od koga'),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='procesuirano',
            field=models.BooleanField(default=False, verbose_name='Odobreno'),
        ),
        migrations.AlterField(
            model_name='emailinbox',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naslov'),
        ),
        migrations.AddIndex(
            model_name='emailinbox',
            index=models.Index(fields=['korisnik', 'procesuirano'], name='core_emaili_korisni_3f2b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailinbox',
            index=models.Index(fields=['pdf_hash'], name='core_emaili_pdf_has_a8935b_idx'),
        ),
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='UploadedDocument',
        ),
    ]
