# Generated by Django 5.0.1 on 2026-02-05 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_calendarevent_korisnik_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPitanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200, verbose_name='Naslov')),
                ('poruka', models.TextField(verbose_name='Poruka')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('u_obradi', 'U obradi'), ('rijeseno', 'Riješeno'), ('zatvoreno', 'Zatvoreno')], default='novo', max_length=20, verbose_name='Status')),
                ('prioritet', models.CharField(choices=[('nizak', 'Nizak'), ('srednji', 'Srednji'), ('visok', 'Visok'), ('hitan', 'Hitan')], default='srednji', max_length=20, verbose_name='Prioritet')),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('datum_azuriranja', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('datum_zatvaranja', models.DateTimeField(blank=True, null=True, verbose_name='Zatvoreno')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_pitanja', to='core.korisnik', verbose_name='Korisnik')),
                ('obradjuje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Obrađuje admin')),
            ],
            options={
                'verbose_name': 'Support Pitanje',
                'verbose_name_plural': 'Support Pitanja',
                'ordering': ['-datum_kreiranja'],
            },
        ),
        migrations.CreateModel(
            name='SupportOdgovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odgovor', models.TextField(verbose_name='Odgovor')),
                ('datum_odgovora', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
                ('pitanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odgovori', to='core.supportpitanje', verbose_name='Pitanje')),
            ],
            options={
                'verbose_name': 'Support Odgovor',
                'verbose_name_plural': 'Support Odgovori',
                'ordering': ['datum_odgovora'],
            },
        ),
        migrations.CreateModel(
            name='SupportSlika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='support_slike/%Y/%m/', verbose_name='Slika')),
                ('datum_upload', models.DateTimeField(auto_now_add=True, verbose_name='Upload-ovano')),
                ('pitanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slike', to='core.supportpitanje', verbose_name='Pitanje')),
            ],
            options={
                'verbose_name': 'Support Slika',
                'verbose_name_plural': 'Support Slike',
                'ordering': ['datum_upload'],
            },
        ),
    ]
