# Generated by Django 5.0.1 on 2026-02-06 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_supportpitanje_supportodgovor_supportslika'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportodgovor',
            name='admin',
        ),
        migrations.AddField(
            model_name='supportodgovor',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='supportodgovor',
            name='je_admin_odgovor',
            field=models.BooleanField(default=False, verbose_name='Admin odgovor'),
        ),
    ]
