# Generated by Django 5.0.1 on 2026-02-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_supportodgovor_admin_supportodgovor_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uplatnica',
            name='primalac',
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='budzetska_organizacija',
            field=models.CharField(default='9999999', max_length=10, verbose_name='Budžetska organizacija'),
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='opstina',
            field=models.CharField(choices=[('001', '001 - Sarajevo - Centar'), ('002', '002 - Banja Luka'), ('003', '003 - Bihać'), ('004', '004 - Banovići'), ('005', '005 - Bijeljina'), ('007', '007 - Bileća'), ('008', '008 - Gradiška'), ('009', '009 - Bosanska Krupa'), ('010', '010 - Bosansko Grahovo'), ('011', '011 - Bosanski Petrovac'), ('012', '012 - Bratunac'), ('013', '013 - Breza'), ('014', '014 - Brod'), ('015', '015 - Bugojno'), ('016', '016 - Busovača'), ('017', '017 - Gračanica'), ('018', '018 - Kozarska Dubica'), ('019', '019 - Šamac'), ('020', '020 - Cazin'), ('021', '021 - Čapljina'), ('022', '022 - Čelinac'), ('023', '023 - Čitluk'), ('024', '024 - Grude'), ('025', '025 - Derventa'), ('026', '026 - Domaljevac-Šamac'), ('027', '027 - Donji Vakuf'), ('028', '028 - Doboj'), ('029', '029 - Drvar'), ('030', '030 - Tomislavgrad'), ('031', '031 - Foča-Ustikolina'), ('032', '032 - Fojnica'), ('033', '033 - Goražde'), ('034', '034 - Gacko'), ('035', '035 - Sarajevo - Hadžići'), ('036', '036 - Glamoč'), ('037', '037 - Gornji Vakuf-Usk.'), ('038', '038 - Sarajevo - Ilidža'), ('039', '039 - Ilijaš'), ('040', '040 - Jablanica'), ('041', '041 - Jajce'), ('042', '042 - Kakanj'), ('043', '043 - Kalesija'), ('044', '044 - Istočno Novo Sarajevo'), ('045', '045 - Kalinovik'), ('046', '046 - Kiseljak'), ('047', '047 - Kladanj'), ('048', '048 - Ključ'), ('049', '049 - Konjic'), ('050', '050 - Ribnik'), ('051', '051 - Kotor Varoš'), ('052', '052 - Kreševo'), ('053', '053 - Kupres (FBiH)'), ('054', '054 - Novo Goražde'), ('056', '056 - Laktaši'), ('058', '058 - Livno'), ('059', '059 - Lopare'), ('060', '060 - Lukavac'), ('061', '061 - Ljubinje'), ('062', '062 - Ljubuški'), ('063', '063 - Maglaj'), ('064', '064 - Modriča'), ('065', '065 - Mrkonjić Grad'), ('066', '066 - Neum'), ('067', '067 - Nevesinje'), ('070', '070 - Novi Travnik'), ('071', '071 - Odžak'), ('072', '072 - Olovo'), ('073', '073 - Orašje'), ('074', '074 - Prijedor'), ('075', '075 - Prnjavor'), ('076', '076 - Ravno'), ('077', '077 - Rogatica'), ('078', '078 - Rudo'), ('079', '079 - Sanski Most'), ('080', '080 - Oštra Luka'), ('081', '081 - Sarajevo - Novi Grad'), ('082', '082 - Sarajevo - Novo Sar.'), ('083', '083 - Sarajevo - Stari Grad'), ('085', '085 - Pale (RS)'), ('086', '086 - Posušje'), ('088', '088 - Kneževo'), ('089', '089 - Sokolac'), ('090', '090 - Srbac'), ('091', '091 - Srebrenica'), ('092', '092 - Srebrenik'), ('093', '093 - Stolac'), ('094', '094 - Čajniče'), ('095', '095 - Šekovići'), ('096', '096 - Šipovo'), ('097', '097 - Han Pijesak'), ('099', '099 - Brčko Distrikt'), ('100', '100 - Široki Brijeg'), ('101', '101 - Živinice'), ('102', '102 - Tešanj'), ('103', '103 - Teslić'), ('104', '104 - Sarajevo - Trnovo (F)'), ('105', '105 - Žepče'), ('106', '106 - Travnik'), ('107', '107 - Trebinje'), ('108', '108 - Tuzla'), ('109', '109 - Ugljevik'), ('110', '110 - Vareš'), ('111', '111 - Zenica'), ('112', '112 - Velika Kladuša'), ('113', '113 - Visoko'), ('114', '114 - Višegrad'), ('115', '115 - Sarajevo - Vogošća'), ('116', '116 - Vitez'), ('117', '117 - Zavidovići'), ('118', '118 - Zvornik'), ('119', '119 - Bužim'), ('120', '120 - Berkovići'), ('121', '121 - Kostajnica'), ('122', '122 - Sarajevo - Trnovo (RS)'), ('123', '123 - Istočni Stari Grad'), ('124', '124 - Istočni Drvar'), ('158', '158 - Istočni Mostar'), ('159', '159 - Jezero'), ('160', '160 - Krupa na Uni'), ('161', '161 - Kupres (RS)'), ('163', '163 - Milići'), ('164', '164 - Petrovac (RS)'), ('165', '165 - Osmaci'), ('166', '166 - Pelagićevo'), ('167', '167 - Vukosavlje'), ('180', '180 - Mostar'), ('181', '181 - Čelić'), ('182', '182 - Doboj Istok'), ('183', '183 - Doboj Jug'), ('184', '184 - Dobretići'), ('185', '185 - Sapna'), ('186', '186 - Teočak'), ('187', '187 - Usora'), ('188', '188 - Pale-Prača'), ('199', '199 - Stanari'), ('241', '241 - Foča (RS)')], default='014', max_length=3, verbose_name='Opština'),
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='poresko_broj',
            field=models.CharField(blank=True, max_length=13, verbose_name='Poresko broj (JIB)'),
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='primalac_adresa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresa primaoca'),
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='primalac_grad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grad primaoca'),
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='primalac_naziv',
            field=models.CharField(default=1, max_length=200, verbose_name='Naziv primaoca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='primalac_tip',
            field=models.CharField(choices=[('PURS', 'Poreska uprava RS'), ('FZO', 'Fond zdravstva RS'), ('CUSTOM', 'Drugi primalac (custom)')], default='PURS', max_length=20, verbose_name='Tip primaoca'),
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='racun_posiljaoca',
            field=models.CharField(default=1, max_length=30, verbose_name='Račun pošiljaoca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='racun_primaoca',
            field=models.CharField(default=1, max_length=30, verbose_name='Račun primaoca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='sifra_placanja',
            field=models.CharField(default='43', max_length=2, verbose_name='Šifra plaćanja'),
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='vrsta_placanja',
            field=models.CharField(choices=[('0', '0 - Redovna/Tekuća uplata'), ('1', '1 - Uplata po rješenju'), ('2', '2 - Uplata po rješenju o prinudnoj naplati'), ('3', '3 - Uplata po rješenju o odgođenom plaćanju'), ('4', '4 - Uplata po rješenju iz inspekcijskog nadzora'), ('5', '5 - Uplata po rješenju o prekršaju'), ('6', '6 - Uplata po rješenju suda'), ('7', '7 - Uplata zaostalih obaveza'), ('8', '8 - Dobrovoljna uplata'), ('9', '9 - Ostale uplate')], default='0', max_length=2, verbose_name='Vrsta plaćanja'),
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='vrsta_prihoda',
            field=models.CharField(blank=True, help_text='712199 - doprinosi, 713111 - porez', max_length=10, verbose_name='Vrsta prihoda'),
        ),
        migrations.AddField(
            model_name='uplatnica',
            name='vrsta_uplate',
            field=models.CharField(choices=[('doprinosi', 'Lični doprinosi'), ('porez', 'Porez na dohodak'), ('custom', 'Custom uplatnica')], default='doprinosi', max_length=20, verbose_name='Vrsta uplate'),
        ),
        migrations.AlterField(
            model_name='uplatnica',
            name='datum',
            field=models.DateField(verbose_name='Datum uplate'),
        ),
        migrations.AlterField(
            model_name='uplatnica',
            name='fajl',
            field=models.FileField(blank=True, null=True, upload_to='uplatnice/'),
        ),
        migrations.AlterField(
            model_name='uplatnica',
            name='iznos',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Iznos (KM)'),
        ),
        migrations.AlterField(
            model_name='uplatnica',
            name='poziv_na_broj',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Poziv na broj'),
        ),
        migrations.AlterField(
            model_name='uplatnica',
            name='svrha',
            field=models.CharField(max_length=200, verbose_name='Svrha uplate'),
        ),
    ]
